baseURL = "https://kowalcj0.github.io"
copyright = ""  # for smart copyright line, leave this blank and check [params.copyright]
defaultContentLanguage = "en"
languageCode = "en-gb"
enableEmoji=true
enableRobotsTXT = true  # generate robots.txt
footnoteReturnLinkContents = "↩"
newContentEditor = "vimx"
paginate = 20
pluralizelisttitles = false  # Don't pluralize titles in lists
theme = "minimo"
title = "Home"

[menu]
  [[menu.main]]
    identifier = "movies"
    name = "Movies"
    url = "/general/movies/"
    weight = 100

  [[menu.main]]
    identifier = "books"
    name = "Books"
    url = "/general/books/"
    weight = 50

  [[menu.main]]
    identifier = "articles"
    name = "Articles"
    url = "/general/articles/"
    weight = 10

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
  posts = "/:year/:month/:day/:title/"
  page = "/:slug/"

# https://gohugo.io/getting-started/configuration-markup
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[params]

  [params.info]
    description = "notes, scribbles, thoughts etc."
    title404 = "Oops! You've found the Mighty Hipster Jedi Gopher!"

  [params.assets]
    favicon = "img/favicon144.ico"
    customCSS = ["css/syntax.css", "css/custom.css"]
    customJS = []
    gopher = "img/gopher.png"  # used in 404 template ( Generator: https://gopherize.me )

  [params.copyright]
    prefix = ""
    holder = "kowalcj0"
    startYear = "2010"
    suffix = ""

  [params.settings]
    # date & time format: https://golang.org/pkg/time/
    dateFormat = "2006-01-02"
    listDateFormat = "2006-01-02"
    archiveDateFormat = "Jan 02"
    hideEntryNavigation = ["page"] # boolean / array of sections
    hideEntryMeta = ["page"] # boolean / array of sections
    showReadingTime = true
    showLastmod = true
    accentColor = "#ffcd00"
    hideMainMenu = false

  [params.sidebar]
    enable = true

  [params.widgets]
    header = ["breadcrumbs"]
    homepage = ["recent_posts"]
    sidebar = ["about", "search", "sidebar_menu", "cat_cloud", "taxonomy_cloud"]
    footer = ["social_menu"]

  [params.opengraph.twitter]
    page = "" # Twitter page username

  [params.seo]
    # Title Separator: - – — · • * ⋆ | ~ « » < >
    titleSeparator = "•"

  [params.social]
    codepen = ""
    email = ""
    facebook = ""
    github = "kowalcj0"
    gitlab = ""
    instagram = ""
    linkedin = ""
    twitter = "januszkowalczyk"
    telegram = ""
    google_scholar = ""
    youtube = ""

  [params.comments]
    enable = true

  # Utterances: https://utteranc.es
  [params.comments.utterances]
    enable = true
    issueTerm = "pathname" # pathname / url / title
    theme = "github-light"

  [params.comments.utterances.github]
    username = "kowalcj0"
    repository = "kowalcj0.github.io"

  [params.search]
    client = "fuse" # algolia / fuse / lunr

